export const ACTIONS = {
  SEND_REGISTRATION: 'SEND_REGISTRATION',
  SEND_REGISTRATION_CONFIRM: 'SEND_REGISTRATION_CONFIRM',
  SEND_LOGIN: 'SEND_LOGIN',
  LOG_OUT: 'LOG_OUT',
  BOOTSTRAP_SAGA: 'BOOTSTRAP_SAGA',
  SEND_FILM: 'SEND_FILM',
  GET_MY_FILMS: 'GET_MY_FILMS',
};
